# Generated by Django 4.2 on 2023-04-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="discount_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
