# Generated by Django 4.2 on 2023-04-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_products_discount_price_alter_products_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=1000)),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("zipcode", models.CharField(max_length=200)),
            ],
        ),
    ]
