# Generated by Django 4.2 on 2023-04-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
